### ISSUE TITLE
RCS Not fully working

### ISSUE THREAD

**Issue by cookiepro688** [martinjanas/Sensum#175]
The recoil control system kind of works, although with every weapon it will go downwards way too much.

**Comment by martinjanas** [comment]
I discovered that setting pitch to 60% works great for spraying on long distances.
I think this is advantage, because the rcs is not focused in one spot, so when you overaim above the head you will still eventually hit the enemy.

(on the left - pitch: 60%, on the right - pitch: 100%)
https://cdn.discordapp.com/attachments/642973675028480044/837740137126297610/unknown.png
