### ISSUE TITLE
Game crashes on load

### ISSUE THREAD

**Issue by phoondos** [martinjanas/Sensum#2]
When I load into any map with nothing toggled/enabled the game crashes. Also crashes with stuff enabled.

**Comment by phoondos** [comment]
Successfully loaded in a map once, but when I died the game crashed.

**Comment by martinjanas** [comment]
Weird,for me the cheat doesnt crash on map load.

There's only 50% chance it will crash while loading to aim_botz,its because of engine prediction.

You need to debug,because it doesnt crash for me,like it crashes for you.

1. Build the cheat in debug. 
2. Attach the debugger to csgo.exe.
3. Inject debugged dll version to csgo.exe,
4. Go into mirage for example.

5. Post the debugger errors here(screenshots)

**Comment by martinjanas** [comment]
Could you please screenshot code of create move.cpp at line 216 ?

**Comment by phoondos** [comment]
is there an eta on when this is getting fixed? this is my favorite legit cheat and i wanna use it

**Comment by trollman4444** [comment]
Well, it's fixed.

**Comment by phoondos** [comment]
game still crashes for me

**Comment by 0x1Eren** [comment]
Same here.
