### ISSUE TITLE
How to get new skins csgo20year cases

### ISSUE THREAD

**Issue by stvnkng** [martinjanas/Sensum#27]
Some can update New knife from the latest case

**Comment by martinjanas** [comment]
Update will come in ~2-3 days, im working on a skins list. https://imgur.com/a/vVRm7S0

Not sure if I will get all ~600 skins to 3 days.

Whats coming in a next update: Sound esp, player info box, grief box, buy info is printed into chat instead of in console, when you hold weapon it automatically selects in aimbot tab, many more.

**Comment by martinjanas** [comment]
So I have updated the game-items.json with all skins, update should be around tomorow,
